const API_BASE_URL = 'https://idr.ensyncit.com'
const apiConfig = {
    setPassword: '/users/set_password',
    createUser: '/users/create',
    loginUser: '/users/login',
    allUsers: '/users/all_users',
    forgotPassword:'/users/forgot_password',
    updateUser:'/users/update',
    addClient:'/client/add',
    getClients:'/client/all',
    updateClient:'client/update',
    getIndustries:'/industry/all',
    getClientById:'/client',
    deleteClient:'/client',
    addClientEmployee:'/client_emp/add',
    getClientEmployeeById:'/client_emp',
    deleteClientEmployee:'/client_emp',
    getLocationByClient:'/location',
    addLocation:'/location/add',
    deleteLocation:'/location',
    client_emp_by_id:'/client_emp/by_id',
    location_by_id:'/location/by_id',
    updateClientEmp:'/client_emp',
    updateLocation:'/location',
    getIdrEmployees:'/idr_emp/all',
    deleteIdrEmp:'/idr_emp/delete',
    addIdrEmployee:'/idr_emp/create',
    updateIdrEmp:'/idr_emp/updateEmp',
    getIdrEmpById:'/idr_emp',
    generateTicket:'/work_order/add',
    addTechnicianToTicket:'/work_order/technician/add',
    addNotesToTicket:'/work_order/note/add',
    getWorkOrderLists:'/work_order/all',
    workOrderbyId:'/work_order/by_id',
    deleteWorkOrder:'/work_order/by_id',
    updateTicket:'/work_order/update_ticket',
    updateTechnician:'/work_order/update_technician',
    updateNotes:'/work_order/update_note',
    getTechniciansByWorkOrder:'/work_order/technician/by_work_order',
    getNotesByWorkOrder:'/work_order/note/by_work_order',
    getWorkOrderByClientId:'/work_order/by_client',
    deleteUser:'/users/delete',
    assignPeople:'/work_order/assignee',
    updateAssignPeople:'/work_order/assignee'
  };
  
  export {API_BASE_URL,apiConfig};
  